reobin/typewritten

- readme.md
- typewritten.zsh-theme
I've added multiline support to "typewritten" with user and host as I need this for the distinction of target nodes when I use multiple terminals. It can be activated by setting the TYPEWRITTEN_MULTILINE=true in .zshrc.
> Added multiline support and some cleanup done

- typewritten.zsh-theme
Closes #4 
Resets colours just after prompt to avoid text changing colour on terminal resize.
> Fix text taking color of prompt when resizing terminal

- readme.md
- typewritten.zsh-theme
Closes #10 
Option is driven by the ``TYPEWRITTEN_SYMBOL`` zsh variable and will replace the ``>`` prompt symbol by whatever its value is.
> feat: Add option to customize the prompt symbol

- readme.md
- typewritten.zsh-theme
Closes #13 
A prefix for the right prompt can be added with the `TYPEWRITTEN_RIGHT_PROMPT_PREFIX` zsh env variable.
> feat: Add right prompt fix option

- readme.md
- typewritten.zsh-theme
Closes #14 
This adds the option to display the git root directory name as well as the current working directory through the `TYPEWRITTEN_GIT_RELATIVE_PATH` variable.
> feat: Add git root display option

- readme.md
- typewritten.zsh-theme
Doesn't display the three dots when current directory is a direct child of the home repo.
Display is now either
```shell
>                 git_repo_root/directory -> master
```
or
```shell
>                 git_repo_root/.../directory -> master
```
depending on nesting.
> feat: Improve git relative path display

- typewritten.zsh-theme
Other plugins like builtin `timer` plugin also use `precmd_functions`, however `typewritten` overwrites it not allowing plugins to display their data.
This PR fixes the problem by appending to `precmd_functions` instead of overwriting.
See https://github.com/ohmyzsh/ohmyzsh/commit/de8d6841b00903f2873a8b009faf7002bfbc1273#diff-8dff0c70d190d2aa1eac09e8613824d4R29
There is also this new way of appending https://github.com/ohmyzsh/ohmyzsh/commit/1ba0af650ac575a7d35b10146d2e7a7b3b2e2ae6#diff-8dff0c70d190d2aa1eac09e8613824d4R30, but I'm not sure if it's active yet (not in my master Oh-My-Zsh yet 🤔, not sure what's the release schedule there). 
Screenshot:
> Append to precmd_functions instead of owerwriting to fix other plugins

- readme.md
- typewritten.zsh-theme
By using the terminal's default foreground colour, the foreground colour would fit both dark and light background colors. This makes the OMZ theme work on both Light and Dark terminal themes.
Let me know if you would like me to make any changes :smiley: I'd love to have this merged with your repository if possible
> Changed Foreground Colour to be Default instead of White

- lib/git.zsh
This fixes the issue I faced in #35. Instead of evaluating the current path with `pwd`, which shows symlinks by default, we now use `pwd -P` to show physical paths, i.e., avoids symlinks, which is how `git rev-parse --show-toplevel` also works.
> Fix issue with right prompt git path with symlinks in super-directory

- readme.md
- typewritten.zsh
https://github.com/reobin/typewritten/issues/37
Add flag `TYPEWRITTEN_DISABLE_RETURN_CODE` for disable return code
Optimally, add a screenshot to the `readme` file of the project for the case with a disabled `return code`, but I can't create a screenshot in the same style with @reobin 
Ball would be glad to help
> [feature] add flag for disable return code

- lib/colors.zsh
Closes #46 
Turns out zsh `%F` handles all kinds of color values if the terminal supports it, including hex, 256, etc.
> feat: Support 24 bit colors for all prompt parts

- lib/colors.zsh
- typewritten.zsh
`TYPEWRITTEN_COLOR_MAPPINGS` option was added.
Possible mappings and their default values:
```bash
["foreground"]="default"
["primary"]="magenta"
["secondary"]="blue"
["accent"]="default"
["info_positive"]="green"
["info_negative"]="red"
["info_neutral_2"]="blue"
["info_neutral_1"]="yellow"
["info_special"]="cyan"
```
They can be defined just like standard sections colors:
```bash
export TYPEWRITTEN_COLOR_MAPPINGS="primary:#9580FF;secondary:#8AFF80;accent:#FFFF80;info_negative:#FF80BF;info_positive:#8AFF80;info_neutral_1:#FF9580;info_neutral_2:#FFFF80;info_special:#80FFEA"
```
Above is an example of a dracula theme.
> feat: Add semantic color mapping options

- typewritten.zsh
> 🐛 Correct bug with variable `code` -> `tw_code`

- typewritten.zsh
Currently, conda doesn't set the `$VIRTUAL_ENV` variable when activating an environment, instead storing the same information under `$CONDA_PREFIX`.  Added this to the script so that the names of conda environments will be displayed.
Note: the order of the `if/elif` statement means that `$VIRTUAL_ENV` will supercede `$CONDA_PREFIX` if both exist...I am not sure if or when this happens e.g. activating a virtualenv environment from within a conda environment.  Because there are so many environment managers, i haven't checked the interplay between each and conda.
> added conda virtual env name to prompt

- README.md
This line appears in the "Manual" section of the [installation docs](https://typewritten.dev/#/installation?id=manual) but not in the readme. 
I know it may have been omitted to funnel users to other ways to install. But not having it in the readme led to some confusion when I was trying to get the theme working by just using the instructions I saw in the readme.
> Add oh-my-zsh note to readme

- typewritten.zsh
closes #107 
Updates `pure` layout to allow for customization of the `TYPEWRITTEN_RELATIVE_PATH`.
This layout uses the `TYPEWRITTEN_RELATIVE_PATH="home"` by default so a check has been added in `tw_get_displayed_wd()`.  
- When `TYPEWRITTEN_RELATIVE_PATH` is not set and the user has selected `TYPEWRITTEN_PROMPT_LAYOUT="pure"` we default to "home". 
-  If the user does have customization for the path set we will use that.    
Cleanup around `tw_get_displayed_wd()` based on changes is also included.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat: Support git relative path on pure layout

- README.md
- scripts/install.sh
- scripts/uninstall.sh
Hi, this pull request started as for the [issue](https://github.com/reobin/typewritten/issues/111) I opened.
I cloned/forked the install script form [Spaceship-prompt](https://github.com/spaceship-prompt/spaceship-prompt/blob/master/scripts/install.sh) and used it as a template for this installer. I tested the installer, both before and afer the changes in my own computer, and everything seems to work perfectly, although more rigorous testing may be required.
This new script solves both issues I had with the old one, which were:
- `async.zsh` and `typewritten.zsh` were not symlinked at all, probably due to the folder it was trying to do so, did not exist.
- the script did not respect the $ZDOTDIR variable.
I hope this helps.
Code seems to be self explainatory, however I am open for …
> fix(installScript): Improved install script

- CONTRIBUTING.md
As the wiki is no longer active, merge its contributing page into
CONTRIBUTING.md. Otherwise, the page's contents are inaccessible unless
one clones the wiki repo.
Fixes #132
> docs: add wiki's contributing page to CONTRIBUTING.md

- typewritten.zsh
When 'TYPEWRITTEN_RELATIVE_PATH' is unset, the 'pure_verbose' layout
does not display the full path. This differs from the default behavior
of the 'pure' layout. As 'pure_verbose' is meant to be a 'pure' variant
with additional information, their default behavior should be the same.
Fixes #130
---
Here's a screenshot of the change compared to #130
> fix: make pure_verbose show full path by default

- docs/installation.md
Add installation information for [antigen](https://github.com/zsh-users/antigen) plugin manager in docs.
> docs: Add antigen plugin manager installation info

- typewritten.zsh
> fix: Use CONDA_PROMPT_MODIFIER to display current conda env
